name: 05 - 1 - Event Filters and Activity Types
on:
  - workflow_dispatch
  # pull_request:
  #   types: 
  #     - opened
  #     - synchronize
  #   branches:
  #     - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show specific PR event
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "Running because a NEW PR was opened against main!"
          else
            echo "Running because new commits were pushed (synchronize) to an existing PR against main!"
          fi